apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-10T22:53:01Z"
  finalizers:
  - tigera.io/cni-protector
  name: calico-cni-plugin
  namespace: calico-system
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
    uid: 5ee0d8a6-d85e-49f6-8be7-b0e3c2419dcf
  resourceVersion: "1362"
  uid: d8b2531c-a363-4900-b929-ca02135ce943
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-10T22:53:01Z"
  name: calico-kube-controllers
  namespace: calico-system
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
    uid: 5ee0d8a6-d85e-49f6-8be7-b0e3c2419dcf
  resourceVersion: "1395"
  uid: 4f321bad-6880-441e-a405-5878514a27f0
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-10T22:53:01Z"
  finalizers:
  - tigera.io/cni-protector
  name: calico-node
  namespace: calico-system
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
    uid: 5ee0d8a6-d85e-49f6-8be7-b0e3c2419dcf
  resourceVersion: "1354"
  uid: 7d5b23cf-ea03-482c-882d-41c81cb204c9
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-10T22:53:01Z"
  name: calico-typha
  namespace: calico-system
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
    uid: 5ee0d8a6-d85e-49f6-8be7-b0e3c2419dcf
  resourceVersion: "1343"
  uid: b4e048db-90f3-4210-a770-3858c549a8af
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-10T22:53:01Z"
  name: default
  namespace: calico-system
  resourceVersion: "1336"
  uid: 168ee121-3360-4577-a26e-345105b8814c
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-10T22:51:42Z"
  name: default
  namespace: tigera-operator
  resourceVersion: "1078"
  uid: 01661e3b-741f-45d4-9fae-46d26ae60e1b
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-01-10T22:51:42Z"
  name: tigera-operator
  namespace: tigera-operator
  resourceVersion: "1144"
  uid: e2954b3b-7135-4c92-bca9-42878c00fce6
